name:                generics
version:             0.1.0.0
github:              "githubuser/generics"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/generics#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - DefaultSignatures
  - TypeOperators
  - ScopedTypeVariables
  - TypeApplications
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - DataKinds
  - TypeFamilies

library:
  source-dirs: src

executables:
  generics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generics

tests:
  generics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generics
